### ISSUE TITLE
Alpha QA

### ISSUE THREAD

**Issue by patyecotera** [dryuen/ist5313-f19-group2#3]
Hello!

- We really liked your color scheme, we felt it fit well with your topic.

- We also enjoyed the paws as your logo!

- We noticed that your links are not working on the left hand side but the ones at the bottom, where it says click to next page, those are working. 

- When navigating through the pages on the 3 modules, we noticed that it does not follow the sequence presented on the left hand side. 

- It's a little confusing to know which topic we are on. Consider adding a hyphen next to Simple tricks to indicate which simple trick is being explained. (example: Simple tricks- Roll Over). 

- Also consider amount of videos and their length in your modules. 

- We felt like we had to scroll too far to see the video. Maybe you could structure your page to where they're more visible.

- You have pages 12 and 13 show the same video, as well as pages 14 and 15 on module 2. Page 2 and 4 also have the same video on module 3.

- We really liked your certificate at the end!

**Comment by c5if** [comment]
The pictures and videos were replaced with more appropriate ones.
